<?php $this->headTitle('Logged In!'); ?>
<img class="heading-icon" src="/img/blue_bottle_open.png" alt="A bottle you've opened. It's bubbling with some kind of delicious-smelling potion.">
<h2>Logged In!</h2>
<p>Thanks, you've given us the access we need so that you can start playing with Tweetist!</p>
<p>You can now <a href="/">return to the main page</a> to start rating your tweets. You'll need to rate a couple messages first before there's enough data to start affecting the stream.</p>