<?php $this->headTitle('Log in with Twitter - Tweetist'); ?>
<img class="heading-icon" src="/img/blue_bottle_closed.png" alt="A stoppered bottle, it could contain a magic potion. You won't know unless you open it.">
<p>Tweetist is an experiment to see if you can apply Bayesian classification to your Twitter stream.</p>
<h2>Log in with Twitter</h2>
<p>You'll need to allow us access to your Twitter account. You have our solemn promise that we won't do anything naughty (like spammy auto-tweets).</p>
<p><a href="<?php echo $this->url(array('action' => 'redirect', 'controller' => 'auth'));?>">Log in with Twitter</a></p>