<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Oops - Tweetist</title>
</head>
<body>
<img class="heading-icon" src="/img/skull_big.png" alt="A terrifying skull representing the scariness of the emotion">
<h2>Oops! Something has gone tragically wrong.</h2>
<p>That's not too surprising though, this is just a sneak-preview and there's barely any error checking going on. When that little tag at the top stops saying "Alpha!" then you can expect better things. For now, why not try something else and hope it works.
<p><a href="/">Carry on...</a></p>
</body>
</html>
